//
// Created by vsensu on 2/17/2020.
//

#ifndef GENERICPROGRAMMINGANDDESIGNPATTERNSAPPLIED_COMMON_H
#define GENERICPROGRAMMINGANDDESIGNPATTERNSAPPLIED_COMMON_H

template <int N1, int N2> class Part
{
public:
    void Run();
};

#endif //GENERICPROGRAMMINGANDDESIGNPATTERNSAPPLIED_COMMON_H
