//
// Created by vsensu on 2/17/2020.
//

#ifndef GENERICPROGRAMMINGANDDESIGNPATTERNSAPPLIED_1_2_H
#define GENERICPROGRAMMINGANDDESIGNPATTERNSAPPLIED_1_2_H

#endif //GENERICPROGRAMMINGANDDESIGNPATTERNSAPPLIED_1_2_H
